// React/src/orig_App.js
import React, {useRef, useState} from "react";
import {Button} from "devextreme-react/button";
import DataGrid, {
  FilterRow, HeaderFilter, SearchPanel,
} from 'devextreme-react/data-grid';

import 'devextreme/dist/css/dx.common.css';
import 'devextreme/dist/css/dx.light.css';

import service from "./data.js";


const orders = service.getOrders();
const style = {margin: '30px'};

export default function App() {
  const dataGridRef = useRef(null);
  const [ds, setDs] = useState([]);

  const getFilteredAndSortedData = React.useCallback(() => {
    const grid = dataGridRef.current.instance;
    const filterExpr = grid.getCombinedFilter(true);
    const dataSource = grid.getDataSource();
    const loadOptions = dataSource.loadOptions();

    dataSource
        .store()
        .load({ filter: filterExpr, sort: loadOptions.sort, group: loadOptions.group })
        .then((result) => {
          // your code...
          setDs(result)
        });
  }, [dataGridRef]);

  return (
      <div style={style}>
        <div><Button onClick={getFilteredAndSortedData} text="Get All Filtered And Sorted Data"/></div>
      <div>
        <DataGrid id="gridContainer"
            ref={ dataGridRef }
            dataSource={orders}
            keyExpr="ID"
            showBorders={true}>
          <FilterRow visible={true} />
          <HeaderFilter visible={true} />
          <SearchPanel visible={true} />
        </DataGrid>
          <br/>
        <div className="title">Loaded data</div>
        <br/>
          <DataGrid
          dataSource={ds}
          keyExpr='ID'
          columnsAutoWidth={true}
          showBorders={true}
          />
      </div>
    </div>
  );
}

// Angular/src/app/orig_app.component.ts
import { Component, ViewChild } from "@angular/core";

import {DxDataGridComponent, DxDataGridModule} from 'devextreme-angular';

import { Order, Service } from './app.service';
import DevExpress from "devextreme";
import dxDataGrid = DevExpress.ui.dxDataGrid;

@Component({
  selector: "app-root",
  templateUrl: "./app.component.html",
  styleUrls: ["./app.component.scss"],
  providers: [Service]
})
export class AppComponent {
  @ViewChild(DxDataGridComponent, { static: false }) dataGrid: DxDataGridComponent | undefined;


  ds: Order[] | null;
  orders: Order[];

  constructor(service: Service) {
    this.orders = service.getOrders();
    this.ds = [];
  }
  getFilteredAndSortedData() {
    let grid: dxDataGrid | undefined = this.dataGrid?.instance;
    let filterExpr = grid?.getCombinedFilter(true);
    const dataSource = grid?.getDataSource();
    const loadOptions = dataSource?.loadOptions();

    dataSource
      ?.store()
      .load({ filter: filterExpr, sort: loadOptions?.sort, group: loadOptions?.group })
      .then((result: any) => {
        // your code...
        this.ds = result;
      });
  }
}

<dx-button text="Get All Filtered And Sorted Data" (onClick)="getFilteredAndSortedData()"></dx-button>
<dx-data-grid
  [dataSource]="orders"
  keyExpr="ID"
  [showBorders]="true" >
  <dxo-filter-row [visible]="true" ></dxo-filter-row>
  <dxo-header-filter [visible]="true"></dxo-header-filter>
  <dxo-search-panel [visible]="true" ></dxo-search-panel>
</dx-data-grid>
<br>
<div class="title">Loaded data</div>
<br>
<dx-data-grid
  [dataSource]="ds"
  keyExpr="ID"
  [showBorders]="true" >
</dx-data-grid>
